# Project settings - General
version: 'v1.0.0' 
title: "Buy Local"
description: "Send Holiday Greetings to your favourite local biz. (And win!)"
baseurl: ""

# Project settings - Analytics
analytics:
    ga_tracking_id: 'UA-12345-5'

# Project settings - Meta
author: "The Tyee"
robots: "index, follow"
revisit: "1 day"
copyright: "&copy; The Tyee 2015"

# Project settings - URLs
urls:
    display: 'buylocal.thetyee.ca'
    privacy: 'http://buylocal.thetyee.ca/privacy'
    credits: 'http://buylocal.thetyee.ca/credits'
    repo: 'https://github.com/TheTyee/buylocal.thetyee.ca'
    issues: 'https://github.com/TheTyee/buylocal.thetyee.ca/issues'

# Project settings - Social
social:
    facebook:
        fb_admins:
            - 12345
        og_url:
        og_image:
        og_sitename:
    twitter:
    gplus:

# Wufoo
wufoo: 'm575vry0pmy7ns'

# GSheets
gdrive: 
  sheet: "Prizes"
  cache_period: 1 minute

# Tabletop
tabletop:
    promos: 'https://docs.google.com/spreadsheets/d/1bpwVmVv4J7ZpXi0BZeG8sH93jhHFD6CCTxtzmin3SeA/pubhtml'

# Jekyll build settings
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - bower.json
  - package.json
  - node_modules
  - bower_components
  - Gruntfile.js
  - Gemfile
  - Gemfile.lock
assets:
  # jekyll-assets pipeline
  # Pathname of the destination of generated (bundled) assets relative
  # to the destination of the root.
  dirname: assets
  # Base URL of assets paths.
  baseurl: /assets/
  sources:
    - ui/js
    - ui/img
    - ui/less
    - ui/css
    - bower_components/jquery/dist/ 
    - bower_components/modernizr/
    - bower_components/bootstrap/dist/js/
    - bower_components/underscore/
    - bower_components/backbone/
    - bower_components/backbone.paginator/lib/
    - bower_components/instafeed.js/
    - bower_components/bootstrap/dist/css/
    - bower_components/fontawesome/css/
    - bower_components/less/
    - bower_components/doctop/dist/
    - bower_components/mustache/
    - bower_components/archieml-js/
    - bower_components/moment/min/
    - bower_components/tabletop/src/
  js_compressor: yui
  css_compressor: yui
  cache: true
  # TODO Remove later
  debug: true
  cachebust: none
