mode: 'preview'
# These overwrite configurations options from _config.yml
# This is for *remote* preview
url: "http://preview.buylocal.thetyee.ca"
api_url: 'http://preview.buylocal.thetyee.ca'

# Different form for development
wufoo: 'mnucytj1hgl1hy'

assets:
  debug: true
  cachebust: none
  cache: true
