mode: 'development'
# These overwrite configurations options from _config.yml
# This is for *remote* development
url: "http://develop.buylocal.thetyee.ca"
api_url: 'http://develop.buylocal.thetyee.ca'

assets:
  debug: true
  cachebust: none
  cache: true
